# Generated by Django 4.0.6 on 2022-07-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user_app.parent', verbose_name='children'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.address'),
        ),
    ]
