# Generated by Django 4.0.6 on 2022-07-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_child_parent_alter_parent_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
    ]
